### ISSUE TITLE
Can we have a multiple swagger UI?

### ISSUE THREAD

**Issue by michnath** [swagger-api/swagger-node-express#193]
I'm developing a system using swagger-node-express and it works great.
Now, I'm preparing to launch the new version of my site.

If currently I have a swagger UI, on my localhost, its address is http://localhost:2052/docs
I want to have a different swagger UI name http://localhost:2052/v2.0/docs with different api.
Is it possible with swagger-node-express because what I knew is we only have one swagger object on an application? CMIIW.

**Comment by fehguy** [comment]
Hi, you mean you are looking to have multiple applications and multiple swagger-ui instances?  I believe this is doable.  Take a look at the express documentation about adding multiple instances in a single server.

**Comment by webron** [comment]
@fehguy - I believe @michnath was looking for a multiple swagger docs from a single app (the ui would be separate). Is that possible?

**Comment by fehguy** [comment]
i don't believe so.  You'll need multiple swagger instances in multiple express apps.  I don't know of how it can be done in one app.

**Comment by michnath** [comment]
I just create multiple two multiple swagger instances in two different express app.

var app = drivers.express();
var newVersionApp = drivers.express();

drivers.swagger.setAppHandler(app);
drivers.newVersionSwagger.setAppHandler(newVersionApp);

both of drivers.swagger and drivers.newVersionSwagger have different APIs.
When I open each docs, both of UI show same api (merged from swagger and newVersionSwagger).

**Comment by michnath** [comment]
Solved.

got a mistake on drivers.js
var newVersionSwagger = require('./swagger/libs/swagger.js'); // THIS IS WRONG

must be
var newVersionSwagger = require('./version2swagger/libs/swagger.js');

Thank you Ron and Tony for your support. Really well appreciated :)
