### ISSUE TITLE
/api-docs is not displaying paths, but they seem to be available.

### ISSUE THREAD

**Issue by azidahaka** [swagger-api/swagger-node-express#197]
```
{
    apiVersion: "http://localhost:8888",
    swaggerVersion: "1.2",
    apis: [
        {
            path: "/pet"
        }
    ]
}
```

I actually set up another route here for /person, but it is not being shown. When I navigate to api-docs/person however, I am presented with the API.

**Comment by fehguy** [comment]
are you adding your resources like such:

https://github.com/swagger-api/swagger-node-express/blob/master/sample-application/app.js#L68-L74

**Comment by azidahaka** [comment]
I used that tutorial at first (and it worked), but not quite doing that. I will try my best to explain. 

Each resource has a config where I am putting the swagger spec. I have access to this, so I am just trying to use that to add the routes. 
    
```
var swagger1 = require('../resources/someResource').swagger;

_.each(config, function(item) {
    if (item.swagger2)  {  // someResource has this 
        console.log(swagger1 === swagger2);  // true
        swagger.addGet(swagger2);                 // does not show up
    }
});

swagger.addGet(swagger1);                        // shows up
```

I'm just confused because although the path does not show up in /api-docs, it still works when I actually navigate to it...

**Comment by azidahaka** [comment]
I changed where I do the swagger stuff in my app so it's earlier on, and now I'm getting the opposite problem. The route is now showing up under the path, but when I navigate to it, it's not there.

**Comment by azidahaka** [comment]
I ended up putting all the swagger stuff earlier on in my app (shortly after I do var app = express()), and it worked.
