### ISSUE TITLE
Passport oAuth

### ISSUE THREAD

**Issue by LeviRosol** [swagger-api/swagger-node-express#205]
Are there any options for integrating oAuth? In previous node / express projects I've used Passport, and end up with routes like so:

```
app.get('/oauth/token', auth.require_basic, routes.auth.oauth_token);
app.post  ('/user', auth.require_auth, routes.user.create);
```

But since swagger-node-express is taking over my routes, I'm at a loss for how to go about defining auth on my end points. Is there a way to do it via `.addValidator`? I've also seen in a couple places where an authorization property is set on the end point spec, but I don't think that's what I'm looking for.

**Comment by LeviRosol** [comment]
There seem to be two bits to the solution for this. First, in addition to the swagger routes, defining routes like so:

```
app.get('/oauth/token', auth.require_basic, routes.auth.oauth_token.action);
app.post('/users/create', auth.require_auth, routes.users.create.action);
```

The second part has two options. One, is to add a parameter to each of your swagger'ed end points like so:

```
parameters : [
                    {"name": "Authorization", "description": "", "defaultValue": "Bearer a_valid_token_here", "paramType":"header","type":"string"}]
```

However, I've found the better and more DRY approach is to alter swagger-ui so that it passes along the header correctly with each request by utilizing the `api_key`. Doing this is pretty simple by overriding the change event like so:

```
      $('#input_apiKey').change(function() {
        var key = $('#input_apiKey')[0].value;
        if(key && key.trim() != "") {
          window.authorizations.add("api_key", new ApiKeyAuthorization("Authorization", "Bearer " + key, "header"));
          console.log("added auth key");
        } else {
          window.authorizations.remove("api_key");
          console.log("removed auth key");
        }
      })
```

Now you can use the oauth/token swagger'ed end point to get a token, and then drop that token in the api_key UI field. Now all requests will have the appropriate Authorization header.

Hope this helps!

**Comment by DaniloOliveira28** [comment]
Hello @LeviRosol ,

What Strategy are you using for the endpoints? I dont know if I use the local or the JWT to my API endpoints.
